// Spare Parts Products Constants

export const PRODUCT_BRANDS = [
  { id: "castrol", name: "Castrol", logo: "/brands/castrol.png" },
  { id: "liqui-moly", name: "Liqui Moly", logo: "/brands/liqui-moly.png" },
  { id: "motul", name: "Motul", logo: "/brands/motul.png" },
  { id: "mannol", name: "Mannol", logo: "/brands/mannol.png" },
  { id: "valvoline", name: "Valvoline", logo: "/brands/valvoline.png" },
  { id: "mobil", name: "Mobil", logo: "/brands/mobil.png" },
  { id: "elf", name: "Elf", logo: "/brands/elf.png" },
  { id: "shell", name: "Shell", logo: "/brands/shell.png" },
  { id: "bmw", name: "BMW", logo: "/brands/bmw.png" },
  { id: "idemitsu", name: "Idemitsu", logo: "/brands/idemitsu.png" },
  { id: "valvoline-2", name: "Valvoline", logo: "/brands/valvoline-2.png" },
];

export const ENGINE_OIL_PRODUCTS = [
  {
    id: "top-tec-4600",
    name: "Top Tec 4600 Motor Oil Top Tec 4600 Motor Oil",
    brand: "LIQUI MOLY",
    brandId: "liqui-moly",
    image: "/products/liqui-moly-top-tec.png",
    price: 499.0,
    originalPrice: 799.0,
    discount: 25,
    rating: 4.5,
    reviews: 234,
    description:
      "Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur adipisci velit...",
    specifications: ["ACEA C3", "API SN"],
    viscosity: "SAE (5W-30)",
  },
  {
    id: "edge-5w30",
    name: "EDGE 5W-30 LL Engine Oil",
    brand: "Castrol",
    brandId: "castrol",
    image: "/products/castrol-edge.png",
    price: 499.0,
    originalPrice: 799.0,
    discount: 25,
    rating: 4.5,
    reviews: 234,
    description:
      "Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur adipisci velit...",
    specifications: ["ACEA C3"],
    viscosity: "SAE (5W-30)",
  },
  {
    id: "mannol-5w30",
    name: "Engine Oil 5W30 API SN 5 Liters",
    brand: "Mannol",
    brandId: "mannol",
    image: "/products/mannol-engine-oil.png",
    price: 499.0,
    originalPrice: 799.0,
    discount: 50,
    rating: 4.5,
    reviews: 234,
    description:
      "Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur adipisci velit...",
    specifications: ["API SN", "ACEA A3/B4"],
    viscosity: "SAE (5W-30)",
  },
  {
    id: "shell-helix-hx8",
    name: "Helix Hx8 5w-30 Api Sn 5 Sl Full-synthetic Engine Oil",
    brand: "Shell",
    brandId: "shell",
    image: "/products/shell-helix.png",
    price: 499.0,
    originalPrice: 799.0,
    discount: 25,
    rating: 4.5,
    reviews: 234,
    description:
      "Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur adipisci velit...",
    specifications: ["API SN", "ACEA A3/B3"],
    viscosity: "SAE (5W-30)",
  },
  {
    id: "mannol-5w40",
    name: "Engine Oil 5W40 API SN 5 Liters",
    brand: "Mannol",
    brandId: "mannol",
    image: "/products/mannol-5w40.png",
    price: 499.0,
    originalPrice: 799.0,
    discount: 25,
    rating: 4.5,
    reviews: 234,
    description:
      "Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur adipisci velit...",
    specifications: ["API SN", "ACEA A3/B4"],
    viscosity: "SAE (5W-40)",
  },
  {
    id: "shell-helix-hx8-2",
    name: "Helix Hx8 5w-30 Api Sn 5 Sl Full-synthetic Engine Oil",
    brand: "Shell",
    brandId: "shell",
    image: "/products/shell-helix-2.png",
    price: 499.0,
    originalPrice: 799.0,
    discount: 25,
    rating: 4.5,
    reviews: 234,
    description:
      "Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur adipisci velit...",
    specifications: ["API SN", "ACEA A3/B3"],
    viscosity: "SAE (5W-30)",
  },
  {
    id: "liqui-moly-top-tec-4600-2",
    name: "Top Tec 4600 Motor Oil Top Tec 4600 Motor Oil",
    brand: "LIQUI MOLY",
    brandId: "liqui-moly",
    image: "/products/liqui-moly-top-tec-2.png",
    price: 499.0,
    originalPrice: 799.0,
    discount: 50,
    rating: 4.5,
    reviews: 234,
    description:
      "Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur adipisci velit...",
    specifications: ["ACEA C3", "API SN"],
    viscosity: "SAE (5W-30)",
  },
  {
    id: "castrol-edge-5w30-2",
    name: "EDGE 5W-30 LL Engine Oil",
    brand: "Castrol",
    brandId: "castrol",
    image: "/products/castrol-edge-2.png",
    price: 499.0,
    originalPrice: 799.0,
    discount: 25,
    rating: 4.5,
    reviews: 234,
    description:
      "Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur adipisci velit...",
    specifications: ["ACEA C3"],
    viscosity: "SAE (5W-30)",
  },
];

export const FILTER_OPTIONS = {
  viscosityOil: [
    { id: "all", name: "All", value: "all" },
    { id: "viscosity-oil", name: "Viscosity Oil", value: "viscosity-oil" },
  ],
  oilManufacturers: [
    { id: "all", name: "All", value: "all" },
    { id: "castrol", name: "Castrol", value: "castrol" },
    { id: "liqui-moly", name: "Liqui Moly", value: "liqui-moly" },
    { id: "mannol", name: "Mannol", value: "mannol" },
    { id: "shell", name: "Shell", value: "shell" },
    { id: "mobil", name: "Mobil", value: "mobil" },
  ],
  engineOilRecommendations: [{ id: "all", name: "All", value: "all" }],
  engineOilSpecifications: [
    { id: "all", name: "All", value: "all" },
    { id: "acea-c3", name: "ACEA C3", value: "ACEA C3" },
  ],
  engineOilViscosity: [
    { id: "sae-5w-30", name: "SAE (5W-30)", value: "SAE (5W-30)" },
    { id: "sae-10w-40", name: "SAE (10W-40)", value: "SAE (10W-40)" },
    { id: "sae-10w-30", name: "SAE (10W-30)", value: "SAE (10W-30)" },
    { id: "sae-5w-40", name: "SAE (5W-40)", value: "SAE (5W-40)" },
    { id: "sae-0w-30", name: "SAE (0W-30)", value: "SAE (0W-30)" },
    { id: "sae-0w-20", name: "SAE (0W-20)", value: "SAE (0W-20)" },
  ],
  engineOilSpecificationsList: [
    { id: "acea-c3", name: "ACEA C3", value: "ACEA C3" },
    { id: "acea-a3-b4", name: "ACEA A3/B4", value: "ACEA A3/B4" },
    { id: "api-sn", name: "API SN", value: "API SN" },
    { id: "acea-c2", name: "ACEA C2", value: "ACEA C2" },
    { id: "acea-a5-b5", name: "ACEA A5/B5", value: "ACEA A5/B5" },
    { id: "acea-a3-b3", name: "ACEA A3/B3", value: "ACEA A3/B3" },
  ],
};
